services:

  app:
    image: ghcr.io/trover204/cdw_project_nhomh:latest
    container_name: laravel_app
    restart: unless-stopped

    ports:
      - "8088:80"

    env_file:
      - ./.env

    volumes:
      - storage_data:/var/www/html/storage

    depends_on:
      - db

    networks:
      - laravel


  db:
    image: mysql:8.4
    container_name: laravel_db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: laravel13
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - laravel


volumes:
  mysql_data:
  storage_data:


networks:
  laravel: