services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.4
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel13
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel: